_BASE_: "../lisa-rcnn-fpn-apm.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  APM: False
  LOAD_PROPOSALS: True
  PROPOSAL_GENERATOR:
    NAME: PrecomputedProposals
  RESNETS:
    DEPTH: 50
INPUT:
  RANDOM_FLIP: none
  MIN_SIZE_TRAIN: (480,)
DATASETS:
  PROPOSAL_FILES_TRAIN: ("/home/pupil/Documents/upgrad/msc/apm_output/inference/proposal_predictions.pth",)

OUTPUT_DIR: "./aln_output"
