_BASE_: "../lisa-centernet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PIXEL_MEAN: [0.40789654, 0.44719302, 0.47026115]
  PIXEL_STD: [0.28863828, 0.27408164, 0.27809835]
SOLVER:
  MAX_ITER: 200000
INPUT:
  RANDOM_FLIP: none
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  RANDOM_FLIP: none
OUTPUT_DIR: "./centernet_local_train"
TEST:
  EVAL_PERIOD: 0
