_BASE_: "../lisa-centernet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
SOLVER:
  MAX_ITER: 200000
INPUT:
  RANDOM_FLIP: none
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  RANDOM_FLIP: none
OUTPUT_DIR: "./centernet_local_train"
TEST:
  EVAL_PERIOD: 0
