_BASE_: "../lisa-centernet.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "centernet_yuv_prepeo_1gc_6wh_8bs/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PIXEL_MEAN: [0.40789654, 0.44719302, 0.47026115]
  PIXEL_STD: [0.28863828, 0.27408164, 0.27809835]
SOLVER:
  MAX_ITER: 200000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 1.0
INPUT:
  RANDOM_FLIP: none
  MIN_SIZE_TRAIN: (360,)
  MAX_SIZE_TRAIN: 360
  MIN_SIZE_TEST: 360
  MAX_SIZE_TEST: 360
  RANDOM_FLIP: none
OUTPUT_DIR: "./centernet_pre"
TEST:
  EVAL_PERIOD: 10000
