_BASE_: "../lisa-centernet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
INPUT:
  RANDOM_FLIP: none
OUTPUT_DIR: "./centernet_out_new"
TEST:
  EVAL_PERIOD: 5000
