MODEL:
  META_ARCHITECTURE: "Centernet"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: CenternetHeads
    NHEADS: 64
  ROI_HEADS:
    NUM_CLASSES: 7
DATASETS:
  TRAIN: ("lisa-train",)
  TEST: ("lisa-val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 900
  # MAX_ITER: 20
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TEST:
  DETECTIONS_PER_IMAGE: 50

INPUT:
  RANDOM_FLIP: none

VERSION: 2
