MODEL:
  META_ARCHITECTURE: "Centernet"
  BACKBONE:
    NAME: build_resnet_fpn_backbone
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: CenternetHeads
    NHEADS: 64
    HM_WEIGHT: 1.0
    WH_WEIGHT: 0.1
    REG_WEIGHT: 1.0
  ROI_HEADS:
    NUM_CLASSES: 7
  CENTERNET:
    FOCAL_LOSS_ALPHA: 2
    FOCAL_LOSS_BETA: 4
    DOWN_SAMPLING: 4
    THRESHOLD: 0.3
DATASETS:
  TRAIN: ("lisa-train",)
  TEST: ("lisa-val",)
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 10.0
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 50000
  # MAX_ITER: 20
INPUT:
  MIN_SIZE_TRAIN: (800.)
TEST:
  DETECTIONS_PER_IMAGE: 50

INPUT:
  RANDOM_FLIP: none

VERSION: 2
